function [colnames, dataall] = table4export(L,cellcentroid,cellarea,...
    cellcirc,cellellipt,cellavgforce,cellmaxforce,celltotalforce,...
    cellnetforce,f0median,kspring)


% ; arrange variable names and data into cell arrays for later export
% ;
% ; inputs: measurement values...
% ; 
% ; outputs:    colnames:   cell array of variable names
% ;             dataall:    cell array of data
% ;
% ; copyright by Ingmar Schoen, ETH Zurich, ingmar.schoen@hest.ethz.ch


colnames = {'cell ID',...
    'Center x [pixel]',...
    'Center y [pixel]',...
    'Area [µm^2]',...
    'Circularity',...
    'Ellipticity',...
    'Average force [nN]',...
    'Traction stress [Pa]',...
    'Maximum force [nN]',...
    'Net force [nN]',...
    'Force resolution [nN]',...
    'Post stiffness [nN/µm]'};
dataall = [1:max(L(:));...
    round(cellcentroid(:,1))';...
    round(cellcentroid(:,2))';...
    round(cellarea);...
    cellcirc;...
    cellellipt;...
    cellavgforce;...
    (celltotalforce-cellnetforce)./cellarea.*1000;...
    cellmaxforce;...
    cellnetforce;...
    f0median*ones([1 max(L(:))]);...
    kspring*ones([1 max(L(:))])];